name: Build and Deploy Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
        
    - name: Build Resume
      run: |
        mkdir -p build
        pdflatex -output-directory=build -jobname=resume src/resume.tex
        
    - name: Create deployment directory
      run: |
        mkdir -p deploy
        cp build/resume.pdf deploy/
        
    - name: Create index.html
      run: |
        cat > deploy/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Maxim Bîrcu - Resume</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    max-width: 800px;
                    margin: 50px auto;
                    padding: 20px;
                    line-height: 1.6;
                    color: #333;
                }
                .header {
                    text-align: center;
                    margin-bottom: 40px;
                }
                .download-btn {
                    display: inline-block;
                    background: #0066cc;
                    color: white;
                    padding: 12px 24px;
                    text-decoration: none;
                    border-radius: 6px;
                    margin: 10px;
                    transition: background 0.3s;
                }
                .download-btn:hover {
                    background: #0052a3;
                }
                .pdf-container {
                    text-align: center;
                    margin: 30px 0;
                }
                .footer {
                    text-align: center;
                    margin-top: 40px;
                    color: #666;
                    font-size: 14px;
                }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Maxim Bîrcu</h1>
                <p>Staff Android Engineer / Tech Lead</p>
            </div>
            
            <div class="pdf-container">
                <a href="./resume.pdf" class="download-btn" download>📄 Download Resume (PDF)</a>
                <a href="./resume.pdf" class="download-btn" target="_blank">👁️ View Resume</a>
            </div>
            
            <div class="pdf-container">
                <embed src="./resume.pdf" type="application/pdf" width="100%" height="800px" />
            </div>
            
            <div class="footer">
                <p>Last updated: <span id="lastUpdated"></span></p>
                <p>Built automatically from <a href="https://github.com/maximbircu/my-resume">GitHub repository</a></p>
            </div>
            
            <script>
                document.getElementById('lastUpdated').textContent = new Date().toLocaleDateString();
            </script>
        </body>
        </html>
        EOF
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true
