name: Build and Deploy Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-full
        
    - name: Build Resume
      run: |
        mkdir -p build
        # Run pdflatex twice to resolve references
        pdflatex -interaction=nonstopmode -output-directory=build -jobname=resume src/resume.tex
        pdflatex -interaction=nonstopmode -output-directory=build -jobname=resume src/resume.tex
        
    - name: Check if PDF was created
      run: |
        if [ ! -f "build/resume.pdf" ]; then
          echo "ERROR: PDF was not created!"
          echo "LaTeX log contents:"
          cat build/resume.log || echo "No log file found"
          exit 1
        else
          echo "PDF created successfully"
          ls -la build/
        fi
        
    - name: Create deployment directory
      run: |
        mkdir -p deploy
        cp build/resume.pdf deploy/
        echo "PDF file size: $(stat -c%s deploy/resume.pdf) bytes"
        
    - name: Create index.html
      run: |
        cat > deploy/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Maxim Bîrcu - Resume</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    margin: 0;
                    padding: 20px;
                    line-height: 1.6;
                    color: #333;
                    background: #f5f5f5;
                }
                .container {
                    max-width: 900px;
                    margin: 0 auto;
                    background: white;
                    border-radius: 8px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                    overflow: hidden;
                }
                .header {
                    text-align: center;
                    padding: 30px 20px 20px;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                }
                .header h1 {
                    margin: 0 0 5px 0;
                    font-size: 2.5em;
                    font-weight: 300;
                }
                .header p {
                    margin: 0;
                    font-size: 1.2em;
                    opacity: 0.9;
                }
                .pdf-container {
                    padding: 0;
                }
                .pdf-container embed {
                    width: 100%;
                    height: 100vh;
                    border: none;
                }
                .footer {
                    text-align: center;
                    padding: 20px;
                    color: #666;
                    font-size: 14px;
                    background: #fafafa;
                    border-top: 1px solid #eee;
                }
                .footer a {
                    color: #667eea;
                    text-decoration: none;
                }
                .footer a:hover {
                    text-decoration: underline;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Maxim Bîrcu</h1>
                    <p>Staff Android Engineer / Tech Lead</p>
                </div>
                
                <div class="pdf-container">
                    <embed src="./resume.pdf" type="application/pdf" />
                </div>
                
                <div class="footer">
                    <p>Last updated: <span id="lastUpdated"></span></p>
                    <p>Built automatically from <a href="https://github.com/maximbircu/my-resume">GitHub repository</a></p>
                </div>
            </div>
            
            <script>
                document.getElementById('lastUpdated').textContent = new Date().toLocaleDateString();
            </script>
        </body>
        </html>
        EOF
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true
